{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Flask\n",
    "Our API will be served directly from our container using Flask, a popular Python Web Server.\n",
    "The Flask application, which will call our prediction function, is defined in the `wsgi.py` file."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "As always, we'll first run some imports to make sure all our requirements are there:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2021-04-13T19:39:12.918898Z",
     "start_time": "2021-04-13T19:38:57.226296Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+https://github.com/tensorflow/examples.git (from -r requirements.txt (line 12))\n",
      "  Cloning https://github.com/tensorflow/examples.git to /tmp/pip-req-build-71tw0a7g\n",
      "  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/examples.git /tmp/pip-req-build-71tw0a7g\n",
      "  Resolved https://github.com/tensorflow/examples.git to commit 8c01781c51a56ee2e78fbbdc696581c6942f92c3\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: Flask in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.0.3)\n",
      "Requirement already satisfied: gunicorn in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (20.1.0)\n",
      "Requirement already satisfied: opencv-python-headless==4.5.* in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (4.5.5.64)\n",
      "Requirement already satisfied: keras==2.8 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2.8.0)\n",
      "Requirement already satisfied: tensorflow==2.8 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (2.8.0)\n",
      "Requirement already satisfied: tensorflow_datasets==4.5.2 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (4.5.2)\n",
      "Requirement already satisfied: scikit-image==0.19.1 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (0.19.1)\n",
      "Requirement already satisfied: scikit-learn==1.0.2 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.0.2)\n",
      "Requirement already satisfied: matplotlib in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (3.4.1)\n",
      "Requirement already satisfied: h5py==2.10.0 in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.10.0)\n",
      "Requirement already satisfied: tensorflow-addons in /opt/app-root/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (0.16.1)\n",
      "Requirement already satisfied: numpy>=1.14.5 in /opt/app-root/lib/python3.8/site-packages (from opencv-python-headless==4.5.*->-r requirements.txt (line 3)) (1.22.3)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (0.2.0)\n",
      "Requirement already satisfied: six>=1.12.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.16.0)\n",
      "Requirement already satisfied: protobuf>=3.9.2 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (3.19.3)\n",
      "Requirement already satisfied: gast>=0.2.1 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (0.4.0)\n",
      "Requirement already satisfied: tensorboard<2.9,>=2.8 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (2.8.0)\n",
      "Requirement already satisfied: absl-py>=0.4.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.0.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.12.1)\n",
      "Requirement already satisfied: keras-preprocessing>=1.1.1 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.1.2)\n",
      "Requirement already satisfied: libclang>=9.0.1 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (12.0.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.6.3)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (3.3.0)\n",
      "Requirement already satisfied: setuptools in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (60.9.3)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.1.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (1.43.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (4.0.1)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (0.23.1)\n",
      "Requirement already satisfied: flatbuffers>=1.12 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (2.0)\n",
      "Requirement already satisfied: tf-estimator-nightly==2.8.0.dev2021122109 in /opt/app-root/lib/python3.8/site-packages (from tensorflow==2.8->-r requirements.txt (line 5)) (2.8.0.dev2021122109)\n",
      "Requirement already satisfied: promise in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (2.3)\n",
      "Requirement already satisfied: tqdm in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (4.62.3)\n",
      "Requirement already satisfied: tensorflow-metadata in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (1.7.0)\n",
      "Requirement already satisfied: dill in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (0.3.4)\n",
      "Requirement already satisfied: importlib-resources in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (5.4.0)\n",
      "Requirement already satisfied: requests>=2.19.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (2.27.1)\n",
      "Requirement already satisfied: scipy>=1.4.1 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (1.6.2)\n",
      "Requirement already satisfied: networkx>=2.2 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (2.6.3)\n",
      "Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (9.0.0)\n",
      "Requirement already satisfied: PyWavelets>=1.1.1 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (1.2.0)\n",
      "Requirement already satisfied: tifffile>=2019.7.26 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (2021.11.2)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (21.3)\n",
      "Requirement already satisfied: imageio>=2.4.1 in /opt/app-root/lib/python3.8/site-packages (from scikit-image==0.19.1->-r requirements.txt (line 7)) (2.13.5)\n",
      "Requirement already satisfied: joblib>=0.11 in /opt/app-root/lib/python3.8/site-packages (from scikit-learn==1.0.2->-r requirements.txt (line 8)) (1.1.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from scikit-learn==1.0.2->-r requirements.txt (line 8)) (3.0.0)\n",
      "Requirement already satisfied: click>=7.1.2 in /opt/app-root/lib/python3.8/site-packages (from Flask->-r requirements.txt (line 1)) (8.0.3)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /opt/app-root/lib/python3.8/site-packages (from Flask->-r requirements.txt (line 1)) (3.1.1)\n",
      "Requirement already satisfied: Werkzeug>=2.0 in /opt/app-root/lib/python3.8/site-packages (from Flask->-r requirements.txt (line 1)) (2.0.2)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /opt/app-root/lib/python3.8/site-packages (from Flask->-r requirements.txt (line 1)) (2.1.2)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 9)) (1.3.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/app-root/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 9)) (2.8.2)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/app-root/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 9)) (0.11.0)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /opt/app-root/lib/python3.8/site-packages (from matplotlib->-r requirements.txt (line 9)) (3.0.6)\n",
      "Requirement already satisfied: typeguard>=2.7 in /opt/app-root/lib/python3.8/site-packages (from tensorflow-addons->-r requirements.txt (line 11)) (2.13.3)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/app-root/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.8->-r requirements.txt (line 5)) (0.37.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/app-root/lib/python3.8/site-packages (from Jinja2>=3.0->Flask->-r requirements.txt (line 1)) (2.0.1)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.19.0->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (2.0.10)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.19.0->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.19.0->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (1.26.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests>=2.19.0->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (2021.10.8)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /opt/app-root/lib/python3.8/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (1.35.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/app-root/lib/python3.8/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (3.3.6)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /opt/app-root/lib/python3.8/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (0.6.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/app-root/lib/python3.8/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (1.8.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/app-root/lib/python3.8/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (0.4.6)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /opt/app-root/lib/python3.8/site-packages (from importlib-resources->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (3.7.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in /opt/app-root/lib/python3.8/site-packages (from tensorflow-metadata->tensorflow_datasets==4.5.2->-r requirements.txt (line 6)) (1.54.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/app-root/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (4.8)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/app-root/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (0.2.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (4.2.4)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/app-root/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (1.3.0)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in /opt/app-root/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (4.10.0)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/app-root/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/app-root/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow==2.8->-r requirements.txt (line 5)) (3.1.1)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now that we have everything in place, we can launch the Flask application.\n",
    "\n",
    "(Please ignore the CUDA errors of warning if you don't have any GPU).\n",
    "\n",
    "This cell will be in a **permanent running state**. That's normal as the webserver process will keep running. When you are **finished** with the test you can just select the cell, and click on the **Stop button** (next to Run)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2021-04-13T20:22:18.706055Z",
     "start_time": "2021-04-13T20:12:31.112873Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app 'wsgi.py' (lazy loading)\n",
      " * Environment: development\n",
      " * Debug mode: on\n",
      "2022-03-28 05:35:54.329757: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 05:35:54.329803: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 05:35:54.330036: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 05:35:54.330237: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 05:36:00.714045: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 05:36:00.714086: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 05:36:00.714283: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 05:36:00.714485: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "2\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "[ WARN:0@9.695] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('dataset/images/test_sample_256_10.jpg'): can't open/read file: check file path/integrity\n",
      "None\n",
      "127.0.0.1 - - [28/Mar/2022 05:36:09] \"\u001b[35m\u001b[1mPOST /predictions HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2091, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2076, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/wsgi.py\", line 17, in object_detection\n",
      "    return jsonify(predict(body))\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 181, in predict\n",
      "    pred_mask = process_file(filename)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 152, in process_file\n",
      "    pred_mask = get_segmentation(filename)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 142, in get_segmentation\n",
      "    input_image = preprocess_image(image_path)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 77, in preprocess_image\n",
      "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
      "cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "2\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "[[[158 175 194]\n",
      "  [174 191 210]\n",
      "  [158 175 196]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[151 168 187]\n",
      "  [164 184 202]\n",
      "  [152 169 190]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[125 144 165]\n",
      "  [144 165 186]\n",
      "  [152 171 192]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " ...\n",
      "\n",
      " [[ 70  68  68]\n",
      "  [ 70  68  68]\n",
      "  [ 71  69  69]\n",
      "  ...\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]]\n",
      "\n",
      " [[ 66  64  64]\n",
      "  [ 67  65  65]\n",
      "  [ 69  67  67]\n",
      "  ...\n",
      "  [ 85  88  92]\n",
      "  [ 85  88  92]\n",
      "  [ 86  89  93]]\n",
      "\n",
      " [[ 58  56  56]\n",
      "  [ 61  59  59]\n",
      "  [ 64  62  62]\n",
      "  ...\n",
      "  [ 88  91  95]\n",
      "  [ 90  93  97]\n",
      "  [ 91  94  98]]]\n",
      "127.0.0.1 - - [28/Mar/2022 05:37:27] \"\u001b[35m\u001b[1mPOST /predictions HTTP/1.1\u001b[0m\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2091, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2076, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/wsgi.py\", line 17, in object_detection\n",
      "    return jsonify(predict(body))\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 181, in predict\n",
      "    pred_mask = process_file(filename)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 152, in process_file\n",
      "    pred_mask = get_segmentation(filename)\n",
      "  File \"/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py\", line 143, in get_segmentation\n",
      "    pred_mask = model(input_image)\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 67, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/opt/app-root/lib/python3.8/site-packages/keras/engine/input_spec.py\", line 264, in assert_input_compatibility\n",
      "    raise ValueError(f'Input {input_index} of layer \"{layer_name}\" is '\n",
      "ValueError: Input 0 of layer \"model_1\" is incompatible with the layer: expected shape=(None, 256, 256, 3), found shape=(1, 128, 128, 3)\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 05:38:33.695766: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 05:38:33.695831: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 05:38:33.696040: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 05:38:33.696241: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "2\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "[[[158 175 194]\n",
      "  [174 191 210]\n",
      "  [158 175 196]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[151 168 187]\n",
      "  [164 184 202]\n",
      "  [152 169 190]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[125 144 165]\n",
      "  [144 165 186]\n",
      "  [152 171 192]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " ...\n",
      "\n",
      " [[ 70  68  68]\n",
      "  [ 70  68  68]\n",
      "  [ 71  69  69]\n",
      "  ...\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]]\n",
      "\n",
      " [[ 66  64  64]\n",
      "  [ 67  65  65]\n",
      "  [ 69  67  67]\n",
      "  ...\n",
      "  [ 85  88  92]\n",
      "  [ 85  88  92]\n",
      "  [ 86  89  93]]\n",
      "\n",
      " [[ 58  56  56]\n",
      "  [ 61  59  59]\n",
      "  [ 64  62  62]\n",
      "  ...\n",
      "  [ 88  91  95]\n",
      "  [ 90  93  97]\n",
      "  [ 91  94  98]]]\n",
      "(1, 256, 256, 3)\n",
      "(256, 256, 1)\n",
      "Figure(1500x1500)\n",
      "127.0.0.1 - - [28/Mar/2022 05:38:37] \"POST /predictions HTTP/1.1\" 200 -\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "2\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "dataset/images/test_sample_256_10.jpg\n",
      "[[[158 175 194]\n",
      "  [174 191 210]\n",
      "  [158 175 196]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[151 168 187]\n",
      "  [164 184 202]\n",
      "  [152 169 190]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " [[125 144 165]\n",
      "  [144 165 186]\n",
      "  [152 171 192]\n",
      "  ...\n",
      "  [255 255 255]\n",
      "  [255 255 255]\n",
      "  [255 255 255]]\n",
      "\n",
      " ...\n",
      "\n",
      " [[ 70  68  68]\n",
      "  [ 70  68  68]\n",
      "  [ 71  69  69]\n",
      "  ...\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]\n",
      "  [ 79  82  86]]\n",
      "\n",
      " [[ 66  64  64]\n",
      "  [ 67  65  65]\n",
      "  [ 69  67  67]\n",
      "  ...\n",
      "  [ 85  88  92]\n",
      "  [ 85  88  92]\n",
      "  [ 86  89  93]]\n",
      "\n",
      " [[ 58  56  56]\n",
      "  [ 61  59  59]\n",
      "  [ 64  62  62]\n",
      "  ...\n",
      "  [ 88  91  95]\n",
      "  [ 90  93  97]\n",
      "  [ 91  94  98]]]\n",
      "(1, 256, 256, 3)\n",
      "(256, 256, 1)\n",
      "Figure(1500x1500)\n",
      "127.0.0.1 - - [28/Mar/2022 05:38:46] \"POST /predictions HTTP/1.1\" 200 -\n",
      "dataset/images/sample_1.jpg\n",
      "2\n",
      "dataset/images/sample_1.jpg\n",
      "dataset/images/sample_1.jpg\n",
      "[[[ 17  45  39]\n",
      "  [ 30  58  52]\n",
      "  [ 43  71  65]\n",
      "  ...\n",
      "  [126 176 164]\n",
      "  [135 188 175]\n",
      "  [168 221 208]]\n",
      "\n",
      " [[ 14  40  34]\n",
      "  [ 21  49  43]\n",
      "  [ 31  57  51]\n",
      "  ...\n",
      "  [ 65 115 103]\n",
      "  [ 50 100  88]\n",
      "  [ 61 114 101]]\n",
      "\n",
      " [[ 15  38  33]\n",
      "  [ 16  42  36]\n",
      "  [ 20  43  38]\n",
      "  ...\n",
      "  [ 48  98  86]\n",
      "  [ 37  87  75]\n",
      "  [ 47  97  85]]\n",
      "\n",
      " ...\n",
      "\n",
      " [[175 172 174]\n",
      "  [177 174 176]\n",
      "  [186 183 185]\n",
      "  ...\n",
      "  [181 180 182]\n",
      "  [182 181 183]\n",
      "  [183 182 184]]\n",
      "\n",
      " [[173 169 174]\n",
      "  [170 166 171]\n",
      "  [173 169 174]\n",
      "  ...\n",
      "  [174 173 175]\n",
      "  [171 170 172]\n",
      "  [169 168 170]]\n",
      "\n",
      " [[170 166 171]\n",
      "  [171 167 172]\n",
      "  [180 176 181]\n",
      "  ...\n",
      "  [178 177 179]\n",
      "  [170 169 171]\n",
      "  [164 163 165]]]\n",
      "(1, 256, 256, 3)\n",
      "(256, 256, 1)\n",
      "Figure(1500x1500)\n",
      "127.0.0.1 - - [28/Mar/2022 05:39:54] \"POST /predictions HTTP/1.1\" 200 -\n",
      "dataset/images/sample_1.jpg\n",
      "2\n",
      "dataset/images/sample_1.jpg\n",
      "dataset/images/sample_1.jpg\n",
      "[[[ 17  45  39]\n",
      "  [ 30  58  52]\n",
      "  [ 43  71  65]\n",
      "  ...\n",
      "  [126 176 164]\n",
      "  [135 188 175]\n",
      "  [168 221 208]]\n",
      "\n",
      " [[ 14  40  34]\n",
      "  [ 21  49  43]\n",
      "  [ 31  57  51]\n",
      "  ...\n",
      "  [ 65 115 103]\n",
      "  [ 50 100  88]\n",
      "  [ 61 114 101]]\n",
      "\n",
      " [[ 15  38  33]\n",
      "  [ 16  42  36]\n",
      "  [ 20  43  38]\n",
      "  ...\n",
      "  [ 48  98  86]\n",
      "  [ 37  87  75]\n",
      "  [ 47  97  85]]\n",
      "\n",
      " ...\n",
      "\n",
      " [[175 172 174]\n",
      "  [177 174 176]\n",
      "  [186 183 185]\n",
      "  ...\n",
      "  [181 180 182]\n",
      "  [182 181 183]\n",
      "  [183 182 184]]\n",
      "\n",
      " [[173 169 174]\n",
      "  [170 166 171]\n",
      "  [173 169 174]\n",
      "  ...\n",
      "  [174 173 175]\n",
      "  [171 170 172]\n",
      "  [169 168 170]]\n",
      "\n",
      " [[170 166 171]\n",
      "  [171 167 172]\n",
      "  [180 176 181]\n",
      "  ...\n",
      "  [178 177 179]\n",
      "  [170 169 171]\n",
      "  [164 163 165]]]\n",
      "(1, 256, 256, 3)\n",
      "(256, 256, 1)\n",
      "Figure(1500x1500)\n",
      "127.0.0.1 - - [28/Mar/2022 05:40:01] \"POST /predictions HTTP/1.1\" 200 -\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 05:40:34.392540: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 05:40:34.392585: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 05:40:34.392788: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 05:40:34.393008: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.~prediction.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/.ipynb_checkpoints/prediction-checkpoint.py', reloading\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 05:40:44.488330: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 05:40:44.488369: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 05:40:44.488555: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 05:40:44.488746: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      "dataset/images/sample_1.jpg\n",
      "2\n",
      "(1, 256, 256, 3)\n",
      "(256, 256, 1)\n",
      "Figure(1500x1500)\n",
      "127.0.0.1 - - [28/Mar/2022 05:40:50] \"POST /predictions HTTP/1.1\" 200 -\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/gunicorn_config-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/gunicorn_config-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/gunicorn_config-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/prediction-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/wsgi-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/wsgi-Copy1.py', reloading\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/wsgi-Copy1.py', reloading\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 06:17:09.385865: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 06:17:09.385906: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 06:17:09.386112: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 06:17:09.386315: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      " * Detected change in '/opt/app-root/src/Semantic-Image-Segmentation-Workshop/gunicorn_config-Copy1.py', reloading\n",
      " * Restarting with watchdog (inotify)\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-835-968\n",
      "2022-03-28 06:17:29.612644: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/opt/app-root/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\n",
      "2022-03-28 06:17:29.612688: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2022-03-28 06:17:29.612911: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyterhub-nb-skasmani-40redhat-2ecom): /proc/driver/nvidia/version does not exist\n",
      "2022-03-28 06:17:29.613107: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "Model Loaded successfully...\n",
      "[INFO] Model loaded successfully...\n",
      "^C\n"
     ]
    }
   ],
   "source": [
    "!FLASK_ENV=development FLASK_APP=wsgi.py flask run"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Once the models have been loaded, our server is ready to take requests. Leave this notebook running,and open `04_SIS_test_application.ipynb`."
   ]
  }
 ],
 "metadata": {
  "finalized": {
   "timestamp": 1618345356814,
   "trusted": true
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
